// Login Types
 const EMAIL_LOGIN_TYPE = "EMAIL";
 const PHONE_LOGIN_TYPE = "PHONE";
 const GOOGLE_LOGIN_TYPE = "GOOGLE";
 const LINKEDIN_LOGIN_TYPE = "LINKEDIN";
 const FACEBOOK_LOGIN_TYPE = "FACEBOOK";
 const LOGIN_TYPE = [
  EMAIL_LOGIN_TYPE,
  PHONE_LOGIN_TYPE,
  GOOGLE_LOGIN_TYPE,
  LINKEDIN_LOGIN_TYPE,
  FACEBOOK_LOGIN_TYPE,
];

 const DEFAULT_LOGIN_TYPE = EMAIL_LOGIN_TYPE;

// Role Type
 const SUPER_ADMIN_ROLE_TYPE = "SUPER_ADMIN";
 const ORGANIZATION_ROLE_TYPE = "ORGANIZATION";
 const STORE_ROLE_TYPE = "STORE";
 const USER_ROLE_TYPE = "USER";
 const AGENCY_ROLE_TYPE = "AGENCY";
 const AGENCY_USER_ROLE_TYPE = "AGENCY_USER";
 const ROLE_TYPE = [
  SUPER_ADMIN_ROLE_TYPE,
  AGENCY_ROLE_TYPE,
  ORGANIZATION_ROLE_TYPE,
  AGENCY_USER_ROLE_TYPE,
  STORE_ROLE_TYPE,
  USER_ROLE_TYPE,
];
 const DEFAULT_ROLE_TYPE = USER_ROLE_TYPE;

// Message Types
 const USER_TEXT_MESSAGE_TYPE = "USER_TEXT_MESSAGE";
 const USER_IMAGE_MESSAGE_TYPE = "USER_IMAGE_MESSAGE";
 const USER_GIF_MESSAGE_TYPE = "USER_GIF_MESSAGE";
 const USER_VIDEO_MESSAGE_TYPE = "USER_VIDEO_MESSAGE";
 const USER_AUDIO_MESSAGE_TYPE = "USER_AUDIO_MESSAGE";
 const SYSTEM_MESSAGE_TYPE = "SYSTEM_MESSAGE";
 const MESSAGE_TYPES = [USER_TEXT_MESSAGE_TYPE, SYSTEM_MESSAGE_TYPE];
 const DEFAULT_MESSAGE_TYPE = USER_TEXT_MESSAGE_TYPE;

// Payment Status types
 const ORDER_RECEIVED = "ORDER_RECEIVED";
 const PAYMENT_UNPAID = "UNPAID";
 const ORDER_CREATED = "ORDER_CREATED";
 const PAYMENT_INITIATED = "PAYMENT_INITIATED";
 const PAYMENT_PENDING = "PAYMENT_PENDING";
 const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
 const PAYMENT_FAILED = "PAYMENT_FAILED";
 const PAYMENT_REFUNDED_GENERATED = "PAYMENT_REFUNDED_GENERATED";
 const PAYMENT_REFUNDED = "PAYMENT_REFUNDED";
 const PAYMENT_STATUS_TYPES = [
  PAYMENT_UNPAID,
  PAYMENT_INITIATED,
  PAYMENT_PENDING,
  PAYMENT_SUCCESS,
  PAYMENT_FAILED,
  PAYMENT_REFUNDED_GENERATED,
  PAYMENT_REFUNDED,
];
 const DEFAULT_PAYMENT_STATUS_TYPE = PAYMENT_UNPAID;

// Product Order Status
 const PRODUCT_ADDED_IN_CART = "PRODUCT_ADDED_IN_CART";
 const PRODUCT_ORDER_INITIATED = "PRODUCT_ORDER_INITIATED";
 const PRODUCT_ORDER_SUCCESS = "PRODUCT_ORDER_SUCCESS";
 const PRODUCT_ORDER_RETURNED = "PRODUCT_ORDER_RETURNED";
 const PRODUCT_ORDER_STATUS_TYPES = [
  PRODUCT_ADDED_IN_CART,
  ORDER_CREATED,
  ORDER_RECEIVED,
  PRODUCT_ORDER_INITIATED,
  PRODUCT_ORDER_SUCCESS,
  PRODUCT_ORDER_RETURNED,
];
 const DEFAULT_PRODUCT_ORDER_STATUS_TYPE = PRODUCT_ADDED_IN_CART;


// Order Status
 const ORDER_CANCLED = "ORDER_CANCLED";
 const ORDER_RETURNED = "ORDER_RETURNED";
 const ORDER_STATUS_TYPES = [
  ORDER_CREATED,
  ORDER_RECEIVED,
  ORDER_CANCLED,
  ORDER_RETURNED,
];
 const DEFAULT_ORDER_STATUS_TYPE = ORDER_CREATED;


// Refund Status types
 const REFUND_GENERATED = "REFUND_GENERATED";
 const REFUND_INITIATED = "REFUND_INITIATED";
 const REFUND_SUCCESS = "REFUND_SUCCESS";
 const REFUND_FAILED = "REFUND_FAILED";
 const REFUND_CANCELED = "REFUND_CANCELED";
 const REFUND_STATUS_TYPES = [
  REFUND_GENERATED,
  REFUND_INITIATED,
  REFUND_SUCCESS,
  REFUND_FAILED,
  REFUND_CANCELED,
];
 const DEFAULT_REFUND_STATUS_TYPE = REFUND_GENERATED;


 const SAVING = "SAVING";
 const CURRENT = "CURRENT";
 const BANK_ACCOUNT_TYPE = [SAVING, CURRENT];

 const INR = "INR";
 const USD = "USD";
 const CURRENCY_TYPES = [INR, USD];
 const DEFAULT_CURRENCY_TYPE = INR;

 const RAZORPAY_GATEWAY = "RAZORPAY_GATEWAY";
 const STRIPE_GATEWAY = "STRIPE_GATEWAY";
 const PAYPAL_GATEWAY = "PAYPAL_GATEWAY";
 const BRAINTREE_GATEWAY = "BRAINTREE_GATEWAY";
 const PAYMENT_GATEWAY_TYPES = [
  RAZORPAY_GATEWAY,
  STRIPE_GATEWAY,
  PAYPAL_GATEWAY,
  BRAINTREE_GATEWAY,
];
 const DEFAULT_PAYMENT_GATEWAY_TYPES = STRIPE_GATEWAY;

 const HOME_LOCATION_TYPE = "HOME_LOCATION_TYPE";
 const OFFICE_LOCATION_TYPE = "OFFICE_LOCATION_TYPE";
 const OTHER_LOCATION_TYPE = "OTHER_LOCATION_TYPE";
 const LOCATION_TYPES = [
  HOME_LOCATION_TYPE,
  OFFICE_LOCATION_TYPE,
  OTHER_LOCATION_TYPE,
];
 const DEFAULT_LOCATION_TYPE = HOME_LOCATION_TYPE;

 const KILO_GRAM = "KILO_GRAM";
 const GRAM = "GRAM";
 const PCS = "PCS";
 const PACKET = "PACKET";
 const BOTTLE = "BOTTLE";
 const POUCH = "POUCH";
 const FEET = "FEET";
 const CENTI_METER = "CENTI_METER";
 const MILI_METER = "MILI_METER";
 const METER = "METER";
 const QUINTAL = "QUINTAL";
 const TON = "TON";
 const SEAT = "SEAT";
 const ITEM_UNITS = [
  KILO_GRAM,
  PCS,
  GRAM,
  PACKET,
  BOTTLE,
  POUCH,
  FEET,
  CENTI_METER,
  MILI_METER,
  METER,
  QUINTAL,
  TON,
  SEAT,
];
 const DEFAULT_ITEM_UNIT = KILO_GRAM;

 const CATALOG_PIN = "CATALOG_PIN";
 const INFO_PIN = "INFO_PIN";
 const DEAL_PIN = "DEAL_PIN";
 const PIN_TYPES = [CATALOG_PIN, INFO_PIN, DEAL_PIN];
 const DEFAULT_PIN_TYPE = CATALOG_PIN;

 const LAST_MINUTE_OFFER = "LAST_MINUTE_OFFER";
 const HOT_DEAL_OFFER = "HOT_DEAL_OFFER";
 const MYSTERY_OFFER = "MYSTERY_OFFER";
 const IN_STORE_OFFER = "IN_STORE_OFFER";
 const OFFER_TYPES = [
  LAST_MINUTE_OFFER,
  HOT_DEAL_OFFER,
  MYSTERY_OFFER,
  IN_STORE_OFFER,
];
 const DEFAULT_OFFER_TYPES = LAST_MINUTE_OFFER;

 const EVERYDAY = "EVERYDAY";
 const WEEKDAYS = "WEEKDAYS";
 const WEEKENDS = "WEEKENDS";
 const SPECIFICDAYS = "SPECIFICDAYS";
 const IMMEDIATE = "IMMEDIATE";
 const FIXED_NUMBER = "FIXED_NUMBER";
 const SCHEDULE_TYPES = [
  FIXED_NUMBER,
  IMMEDIATE,
  WEEKENDS,
  WEEKDAYS,
  EVERYDAY,
  SPECIFICDAYS,
];
 const DEFAULT_SCHEDULE_TYPES = IMMEDIATE;

 const SUNDAY = "SUNDAY";
 const MONDAY = "MONDAY";
 const TUESDAY = "TUESDAY";
 const WEDNESDAY = "WEDNESDAY";
 const THURSDAY = "THURSDAY";
 const FRIDAY = "FRIDAY";
 const SATURDAY = "SATURDAY";
 const SCHEDULE_DAYS = [
  SUNDAY,
  MONDAY,
  TUESDAY,
  WEDNESDAY,
  THURSDAY,
  FRIDAY,
  SATURDAY,
];

//DISCOUNT Units
 const PERCENT = "PERCENT";
 const UNIT = "UNIT";
 const AMOUNT = "AMOUNT";
 const DISCOUNT_UNIT_TYPES = [PERCENT, UNIT, AMOUNT];
 const DEFAULT_DISCOUNT_UNIT_TYPES = PERCENT;

 const UNSEEN = "UNSEEN";
 const VIEWED = "VIEWED";
 const CLAIMED = "CLAIMED";
 const REDEEMED = "REDEEMED";
 const WALLET_STATUS = [UNSEEN, VIEWED, CLAIMED, REDEEMED];
 const DEFAULT_WALLET_STATUS = VIEWED;

// Logs Types
 const AUTHENTICATION_EVENT = "AUTHENTICATION";
 const INVENTORY_EVENT = "INVENTORY";
 const GENERAL_EVENT = "GENERAL";
 const PAYMENT_EVENT = "PAYMENT";
 const LOGS_TYPE = [
  GENERAL_EVENT,
  AUTHENTICATION_EVENT,
  INVENTORY_EVENT,
  PAYMENT_EVENT,
];
 const DEFAULT_LOGS_TYPE = GENERAL_EVENT;

// Logs Sub Types
 const LOGIN_EVENT = "LOGIN";
 const SIGNUP_EVENT = "SIGNUP";
 const USER_VERIFIED_EVENT = "USER_VERIFIED";
 const RESET_PASSWORD_EVENT = "RESET_PASSWORD";
 const UPDATE_PROFILE_EVENT = "UPDATE_PROFILE";
 const CHANGE_PASSWORD_EVENT = "CHANGE_PASSWORD";
 const CLOSE_ACCOUNT_EVENT = "CLOSE_ACCOUNT";
 const PIN_CREATED_EVENT = "PIN_CREATED";
 const PIN_UPDATED_EVENT = "PIN_UPDATED";
 const PIN_VIEWED_EVENT = "PIN_VIEWED";
 const PIN_CLAIMED_EVENT = "PIN_CLAIMED";
 const PIN_REDEEMED_EVENT = "PIN_REDEEMED";
 const PIN_DELETED_EVENT = "PIN_DELETED_EVENT";
 const PAYMENT_SUCCESS_EVENT = "PAYMENT_SUCCESS";
 const PAYMENT_FAILED_EVENT = "PAYMENT_FAILED";
 const PAYMENT_INITIATED_EVENT = "PAYMENT_INITIATED";
 const WALLET_ADDED_EVENT = "PAYMENT_INITIATED";
 const WALLET_UPDATED_EVENT = "PAYMENT_INITIATED";
 const CART_UPDATED_EVENT = "PAYMENT_INITIATED";
 const CART_ADDED_EVENT = "PAYMENT_INITIATED";
 const CART_REMOVED_EVENT = "PAYMENT_INITIATED";
 const REFUND_SUCCESS_EVENT = "REFUND_SUCCESS";
 const REFUND_INITIATED_EVENT = "REFUND_INITIATED";
 const REFUND_REJECTED_EVENT = "REFUND_REJECTED";
 const REFUND_FAILED_EVENT = "REFUND_FAILED";
 const ORDER_RECEIVED_EVENT = "ORDER_RECEIVED";
 const ORDER_CREATED_EVENT = "ORDER_CREATED_EVENT";
 const ORDER_UPDATED_EVENT = "ORDER_UPDATED_EVENT";
 const ORDER_CANCELED_EVENT = "ORDER_CANCELED";
 const ORDER_PLACED_EVENT = "ORDER_CANCELED";
 const LOGS_SUB_TYPE = [
  GENERAL_EVENT,
  LOGIN_EVENT,
  SIGNUP_EVENT,
  RESET_PASSWORD_EVENT,
  USER_VERIFIED_EVENT,
  UPDATE_PROFILE_EVENT,
  CHANGE_PASSWORD_EVENT,
  CLOSE_ACCOUNT_EVENT,
  PIN_CREATED_EVENT,
  PIN_UPDATED_EVENT,
  PIN_VIEWED_EVENT,
  PIN_CLAIMED_EVENT,
  PIN_REDEEMED_EVENT,
  PIN_DELETED_EVENT,
  PAYMENT_SUCCESS_EVENT,
  CART_UPDATED_EVENT,
  CART_ADDED_EVENT,
  CART_REMOVED_EVENT,
  PAYMENT_FAILED_EVENT,
  PAYMENT_INITIATED_EVENT,
  REFUND_SUCCESS_EVENT,
  WALLET_ADDED_EVENT,
  WALLET_UPDATED_EVENT,
  REFUND_INITIATED_EVENT,
  REFUND_REJECTED_EVENT,
  REFUND_FAILED_EVENT,
  ORDER_RECEIVED_EVENT,
  REFUND_REJECTED_EVENT,
  ORDER_CANCELED_EVENT,
  ORDER_PLACED_EVENT,
  ORDER_CREATED_EVENT,
  ORDER_UPDATED_EVENT,
];
 const DEFAULT_LOGS_SUB_TYPE = GENERAL_EVENT;


// Payment Type
 const ONLINE = "ONLINE"
 const INSTORE = "INSTORE"
 const ONDELIVERY = "ONDELIVERY"
 const PAYMENT_TYPES = [ONLINE, INSTORE, ONDELIVERY]
 const DEFAULT_PAYMENT_TYPE = INSTORE


 const LAST_MINUTE_PIN = "LAST_MINUTE_PIN";
 const FLAT_DISCOUNT_PIN = "FLAT_DISCOUNT_PIN";
 const PIN_CATEGORY_TYPES = [
  LAST_MINUTE_PIN,
  FLAT_DISCOUNT_PIN,

];
 const DEFAULT_PIN_CATEGORY_TYPES = FLAT_DISCOUNT_PIN




 module.exports = {




    PIN_TYPES ,
    DEFAULT_PIN_TYPE ,
    OFFER_TYPES ,
    DEFAULT_OFFER_TYPES ,
    DEFAULT_SCHEDULE_TYPES ,
    SCHEDULE_TYPES ,
    DISCOUNT_UNIT_TYPES ,
    DEFAULT_DISCOUNT_UNIT_TYPES ,
    SCHEDULE_DAYS ,
    DEFAULT_PAYMENT_TYPE ,
    PAYMENT_TYPES ,
    PIN_CATEGORY_TYPES ,
    DEFAULT_PIN_CATEGORY_TYPES ,
    CURRENCY_TYPES,
    DEFAULT_CURRENCY_TYPE,
    DEFAULT_ITEM_UNIT ,
    ITEM_UNITS,
    LOGIN_TYPE,
    DEFAULT_LOGIN_TYPE,
    ROLE_TYPE,
    LOCATION_TYPES,
    DEFAULT_LOCATION_TYPE,
    WALLET_STATUS,
    DEFAULT_WALLET_STATUS,
    PAYMENT_STATUS_TYPES,
    DEFAULT_PRODUCT_ORDER_STATUS_TYPE ,
    PRODUCT_ORDER_STATUS_TYPES ,
    PAYMENT_STATUS_TYPES ,
    DEFAULT_PAYMENT_STATUS_TYPE,
    DEFAULT_ORDER_STATUS_TYPE ,
    ORDER_STATUS_TYPES ,
    REFUND_STATUS_TYPES ,
    DEFAULT_REFUND_STATUS_TYPE ,
    BANK_ACCOUNT_TYPE ,
    PAYMENT_UNPAID ,
    PAYMENT_SUCCESS ,
    UNSEEN ,
    VIEWED,
    CLAIMED ,
    REDEEMED,
    PAYMENT_FAILED,
    PRODUCT_ORDER_INITIATED  ,
    PRODUCT_ORDER_SUCCESS  ,
    PRODUCT_ORDER_RETURNED,
    ORDER_RECEIVED
    
 }


